name: Publish Docker image and deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  PORTAINER_URL: "https://docker.jgallego.es/api"

jobs:
  refresh_container:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
