name: Publish Docker image and deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  PORTAINER_URL: "https://docker.jgallego.es/api"

jobs:  
  refresh_container:
    name: Push Docker image to Portainer
    runs-on: ubuntu-latest
    steps:    
      - name: Portainer auth
        id: authRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ env.PORTAINER_URL }}/auth'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"username": "${{ secrets.DOCKER_USERNAME }}", "password": "${{ secrets.DOCKER_PASSWORD }}"}'
          
      - name: Remove existing container
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ env.PORTAINER_URL }}/endpoints/2/docker/containers/mimo-website?v=true&force=true'
          method: 'DELETE'
          customHeaders: '{"Authorization": "Bearer ${{ fromJson(steps.authRequest.outputs.response).jwt }}"}'
          
      - name: Remove unused images
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ env.PORTAINER_URL }}/endpoints/2/docker/images/prune?filters={"dangling":{"false":true}}'
          method: 'POST'
          customHeaders: '{"Authorization": "Bearer ${{ fromJson(steps.authRequest.outputs.response).jwt }}"}'
          
      - name: deploy new container
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          method: 'POST'
          timeout: 1200000

      - name: Clean unused images
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ env.PORTAINER_URL }}/endpoints/2/docker/images/prune?filters={"dangling":{"false":true}}'
          method: 'POST'
          customHeaders: '{"Authorization": "Bearer ${{ fromJson(steps.authRequest.outputs.response).jwt }}"}'
