name: Publish Docker image and deploy

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Get current date # get the date of the build
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Log into registry
        run: docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build the Docker image
        if: success() && github.event_name != 'pull_request'
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ steps.date.outputs.date }} --tag ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

      - name: Docker Push
        if: success() && github.event_name != 'pull_request'
        run: docker push ${{ github.event.repository.name }} --all-tags
      
      - name: Call portainer webhook
        if: success() && github.event_name != 'pull_request'
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          headers: '{"repository": "${{ github.event.repository.name }}"}'
          body: '{"event": "deployment", "repository": "${{ github.event.repository.name }}"}'
